#!/bin/bash
PROJECT_PATH=$(dirname $(readlink -f "$0"))

cd $PROJECT_PATH
docker-compose stop web redis

echo "[START in parallel] docker containers build started. Please wait while it finished"
docker-compose build > build-output.txt 2>&1 &

source .env 2>/dev/null

touch build-output.txt && cat build-output.txt && rm build-output.txt

docker-compose up -d --force-recreate web redis nginx
